module.exports = [
  ['couchDB_ET', 'Easy Travel Couch DB'],
  ['EasyTravelWebserver:18079', 'Easy Travel web server on port 18079'],
  [/\b(https?:\/\/)?(\w+)\.(com|org|net)(\/[^\s.,]*)?/, '$2 dot $3'],
  [/\b([a-zA-Z]+)\.(\w\w\w?)\b/, '$1 dot <say-as interpret-as="spell-out">$2</say-as>'],
  ['TAL'],
  ['couchdb', 'Couch DB'],
  [/\.NET/, 'dot net'],
  ['DB'],
  ['API'],
  ['SQL'],
  ['Postgresql', 'Postgres <say-as interpret-as="spell-out">QL</say-as>'],
  ['MSSQL'],
  ['JS'],
];
