/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/auth/auth-login/auth-login.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../src/app/shared/davis.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import11 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import14 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import16 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/common/src/directives/ng_if';
import * as import20 from '@angular/forms/src/directives/default_value_accessor';
import * as import21 from '@angular/forms/src/directives/validators';
import * as import22 from '@angular/forms/src/validators';
import * as import23 from '@angular/forms/src/directives/control_value_accessor';
import * as import24 from '@angular/forms/src/directives/ng_model';
import * as import25 from '@angular/forms/src/directives/ng_control';
import * as import26 from '@angular/forms/src/directives/ng_control_status';
import * as import27 from '@angular/forms/src/directives/ng_form';
import * as import28 from '@angular/forms/src/directives/control_container';
import * as import29 from '@angular/core/src/change_detection/change_detection_util';
export class Wrapper_AuthLoginComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AuthLoginComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.AuthLoginComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AuthLoginComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AuthLoginComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AuthLoginComponent>;
  _AuthLoginComponent_0_3:Wrapper_AuthLoginComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AuthLoginComponent_Host0,renderType_AuthLoginComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'auth-login',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AuthLoginComponent0(this.viewUtils,this,0,this._el_0);
    this._AuthLoginComponent_0_3 = new Wrapper_AuthLoginComponent(this.injectorGet(import8.DavisService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex));
    this.compView_0.create(this._AuthLoginComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AuthLoginComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AuthLoginComponent) && (0 === requestNodeIndex))) { return this._AuthLoginComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AuthLoginComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AuthLoginComponentNgFactory:import7.ComponentFactory<import0.AuthLoginComponent> = new import7.ComponentFactory<import0.AuthLoginComponent>('auth-login',View_AuthLoginComponent_Host0,import0.AuthLoginComponent);
const styles_AuthLoginComponent:any[] = ([] as any[]);
var renderType_AuthLoginComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AuthLoginComponent,{});
export class View_AuthLoginComponent0 extends import1.AppView<import0.AuthLoginComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _NgForm_12_3:import10.Wrapper_NgForm;
  _ControlContainer_12_4:any;
  _NgControlStatusGroup_12_5:import11.Wrapper_NgControlStatusGroup;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _vc_14:import12.ViewContainer;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import13.Wrapper_NgIf;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _DefaultValueAccessor_23_3:import14.Wrapper_DefaultValueAccessor;
  _RequiredValidator_23_4:import15.Wrapper_RequiredValidator;
  _NG_VALIDATORS_23_5:any[];
  _NG_VALUE_ACCESSOR_23_6:any[];
  _NgModel_23_7:import16.Wrapper_NgModel;
  _NgControl_23_8:any;
  _NgControlStatus_23_9:import11.Wrapper_NgControlStatus;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _DefaultValueAccessor_34_3:import14.Wrapper_DefaultValueAccessor;
  _RequiredValidator_34_4:import15.Wrapper_RequiredValidator;
  _NG_VALIDATORS_34_5:any[];
  _NG_VALUE_ACCESSOR_34_6:any[];
  _NgModel_34_7:import16.Wrapper_NgModel;
  _NgControl_34_8:any;
  _NgControlStatus_34_9:import11.Wrapper_NgControlStatus;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AuthLoginComponent0,renderType_AuthLoginComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','page'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','title title-auth'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'img',new import3.InlineArray4(4,'id','davis-logo','src','./assets/img/Davis_Avatar_512x512_blue_bg.png'),(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'id','davis-logo-text'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Davis',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','content content-auth'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_12_3 = new import10.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_12_4 = this._NgForm_12_3.context;
    this._NgControlStatusGroup_12_5 = new import11.Wrapper_NgControlStatusGroup(this._ControlContainer_12_4);
    this._text_13 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_12,(null as any));
    this._vc_14 = new import12.ViewContainer(14,12,this,this._anchor_14);
    this._TemplateRef_14_5 = new import17.TemplateRef_(this,14,this._anchor_14);
    this._NgIf_14_6 = new import13.Wrapper_NgIf(this._vc_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_12,'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','flex-item full-width'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Email',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_18,'input',new import3.InlineArray16(12,'autofocus','','name','email','ngModel','','placeholder','john.smith@example.com','required','','type','email'),(null as any));
    this._DefaultValueAccessor_23_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_23));
    this._RequiredValidator_23_4 = new import15.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_23_5 = [this._RequiredValidator_23_4.context];
    this._NG_VALUE_ACCESSOR_23_6 = [this._DefaultValueAccessor_23_3.context];
    this._NgModel_23_7 = new import16.Wrapper_NgModel(this._ControlContainer_12_4,this._NG_VALIDATORS_23_5,(null as any),this._NG_VALUE_ACCESSOR_23_6);
    this._NgControl_23_8 = this._NgModel_23_7.context;
    this._NgControlStatus_23_9 = new import11.Wrapper_NgControlStatus(this._NgControl_23_8);
    this._text_24 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._text_25 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._text_26 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_12,'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'div',new import3.InlineArray2(2,'class','flex-item full-width'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n                    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Password',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n                    ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_29,'input',new import3.InlineArray8(8,'name','password','placeholder','••••••••••','required','','type','password'),(null as any));
    this._DefaultValueAccessor_34_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_34));
    this._RequiredValidator_34_4 = new import15.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_34_5 = [this._RequiredValidator_34_4.context];
    this._NG_VALUE_ACCESSOR_34_6 = [this._DefaultValueAccessor_34_3.context];
    this._NgModel_34_7 = new import16.Wrapper_NgModel(this._ControlContainer_12_4,this._NG_VALIDATORS_34_5,(null as any),this._NG_VALUE_ACCESSOR_34_6);
    this._NgControl_34_8 = this._NgModel_34_7.context;
    this._NgControlStatus_34_9 = new import11.Wrapper_NgControlStatus(this._NgControl_34_8);
    this._text_35 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._text_36 = this.renderer.createText(this._el_27,'\n            ',(null as any));
    this._text_37 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_12,'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'div',new import3.InlineArray2(2,'class','flex-item next'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                    ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'button',new import3.InlineArray4(4,'class','content-save-button log-in','type','submit'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'Sign in',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._text_45 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._text_46 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._text_47 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._text_48 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_12));
    this._NgForm_12_3.subscribe(this,this.eventHandler(this.handleEvent_12),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_23));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_34,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_34));
    this._NgModel_34_7.subscribe(this,this.eventHandler(this.handleEvent_34),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import19.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6.context; }
    if (((token === import20.DefaultValueAccessor) && (23 === requestNodeIndex))) { return this._DefaultValueAccessor_23_3.context; }
    if (((token === import21.RequiredValidator) && (23 === requestNodeIndex))) { return this._RequiredValidator_23_4.context; }
    if (((token === import22.NG_VALIDATORS) && (23 === requestNodeIndex))) { return this._NG_VALIDATORS_23_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (23 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_23_6; }
    if (((token === import24.NgModel) && (23 === requestNodeIndex))) { return this._NgModel_23_7.context; }
    if (((token === import25.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_8; }
    if (((token === import26.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_9.context; }
    if (((token === import20.DefaultValueAccessor) && (34 === requestNodeIndex))) { return this._DefaultValueAccessor_34_3.context; }
    if (((token === import21.RequiredValidator) && (34 === requestNodeIndex))) { return this._RequiredValidator_34_4.context; }
    if (((token === import22.NG_VALIDATORS) && (34 === requestNodeIndex))) { return this._NG_VALIDATORS_34_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (34 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_34_6; }
    if (((token === import24.NgModel) && (34 === requestNodeIndex))) { return this._NgModel_34_7.context; }
    if (((token === import25.NgControl) && (34 === requestNodeIndex))) { return this._NgControl_34_8; }
    if (((token === import26.NgControlStatus) && (34 === requestNodeIndex))) { return this._NgControlStatus_34_9.context; }
    if (((token === import27.NgForm) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NgForm_12_3.context; }
    if (((token === import28.ControlContainer) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._ControlContainer_12_4; }
    if (((token === import26.NgControlStatusGroup) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NgControlStatusGroup_12_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    this._NgControlStatusGroup_12_5.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_14_0_0:any = this.context.loginError;
    this._NgIf_14_6.check_ngIf(currVal_14_0_0,throwOnChange,false);
    this._NgIf_14_6.ngDoCheck(this,this._anchor_14,throwOnChange);
    this._DefaultValueAccessor_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_1_0:any = '';
    this._RequiredValidator_23_4.check_required(currVal_23_1_0,throwOnChange,false);
    this._RequiredValidator_23_4.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_2_0:any = 'email';
    this._NgModel_23_7.check_name(currVal_23_2_0,throwOnChange,false);
    const currVal_23_2_1:any = '';
    this._NgModel_23_7.check_model(currVal_23_2_1,throwOnChange,false);
    this._NgModel_23_7.ngDoCheck(this,this._el_23,throwOnChange);
    this._NgControlStatus_23_9.ngDoCheck(this,this._el_23,throwOnChange);
    this._DefaultValueAccessor_34_3.ngDoCheck(this,this._el_34,throwOnChange);
    const currVal_34_1_0:any = '';
    this._RequiredValidator_34_4.check_required(currVal_34_1_0,throwOnChange,false);
    this._RequiredValidator_34_4.ngDoCheck(this,this._el_34,throwOnChange);
    const currVal_34_2_0:any = 'password';
    this._NgModel_34_7.check_name(currVal_34_2_0,throwOnChange,false);
    const currVal_34_2_1:any = this.context.password;
    this._NgModel_34_7.check_model(currVal_34_2_1,throwOnChange,false);
    this._NgModel_34_7.ngDoCheck(this,this._el_34,throwOnChange);
    this._NgControlStatus_34_9.ngDoCheck(this,this._el_34,throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_12_5.checkHost(this,this,this._el_12,throwOnChange);
    this._RequiredValidator_23_4.checkHost(this,this,this._el_23,throwOnChange);
    this._NgControlStatus_23_9.checkHost(this,this,this._el_23,throwOnChange);
    this._RequiredValidator_34_4.checkHost(this,this,this._el_34,throwOnChange);
    this._NgControlStatus_34_9.checkHost(this,this,this._el_34,throwOnChange);
  }
  destroyInternal():void {
    this._vc_14.destroyNestedViews();
    this._NgModel_23_7.ngOnDestroy();
    this._NgModel_34_7.ngOnDestroy();
    this._NgForm_12_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 14)) { return new View_AuthLoginComponent1(this.viewUtils,this,14,this._anchor_14,this._vc_14); }
    return (null as any);
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_12_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.login(this._NgForm_12_3.context)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_23_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_34(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_34_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.password = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_AuthLoginComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AuthLoginComponent1,renderType_AuthLoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_5 = import29.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','flex-item full-width error'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5:any = import3.inlineInterpolate(1,'\n                    ',this.parentView.context.loginError,'\n                ');
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}