/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/config/config-user/config-user.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../src/app/config/config.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from './config-user.component.css.shim';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import13 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import14 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import16 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import17 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import18 from '../../../../node_modules/@angular/forms/src/directives/select_control_value_accessor.ngfactory';
import * as import19 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import20 from '@angular/core/src/change_detection/change_detection_util';
import * as import21 from '@angular/core/src/linker/template_ref';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import24 from '@angular/common/src/directives/ng_if';
import * as import25 from '@angular/forms/src/directives/default_value_accessor';
import * as import26 from '@angular/forms/src/directives/validators';
import * as import27 from '@angular/forms/src/validators';
import * as import28 from '@angular/forms/src/directives/control_value_accessor';
import * as import29 from '@angular/forms/src/directives/ng_model';
import * as import30 from '@angular/forms/src/directives/ng_control';
import * as import31 from '@angular/forms/src/directives/ng_control_status';
import * as import32 from '@angular/common/src/directives/ng_for';
import * as import33 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import34 from '@angular/forms/src/directives/ng_form';
import * as import35 from '@angular/forms/src/directives/control_container';
import * as import36 from '../../../../node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.ngfactory';
import * as import37 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import38 from '../../../../node_modules/@angular/forms/src/directives/checkbox_value_accessor.ngfactory';
import * as import39 from '@angular/forms/src/directives/checkbox_value_accessor';
export class Wrapper_ConfigUserComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ConfigUserComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.ConfigUserComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ConfigUserComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ConfigUserComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ConfigUserComponent>;
  _ConfigUserComponent_0_3:Wrapper_ConfigUserComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ConfigUserComponent_Host0,renderType_ConfigUserComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'config-user',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ConfigUserComponent0(this.viewUtils,this,0,this._el_0);
    this._ConfigUserComponent_0_3 = new Wrapper_ConfigUserComponent(this.injectorGet(import8.ConfigService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex));
    this.compView_0.create(this._ConfigUserComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ConfigUserComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ConfigUserComponent) && (0 === requestNodeIndex))) { return this._ConfigUserComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ConfigUserComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ConfigUserComponentNgFactory:import7.ComponentFactory<import0.ConfigUserComponent> = new import7.ComponentFactory<import0.ConfigUserComponent>('config-user',View_ConfigUserComponent_Host0,import0.ConfigUserComponent);
const styles_ConfigUserComponent:any[] = [import10.styles];
var renderType_ConfigUserComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_ConfigUserComponent,{});
export class View_ConfigUserComponent0 extends import1.AppView<import0.ConfigUserComponent> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import11.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import12.Wrapper_NgIf;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _vc_6:import11.ViewContainer;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import12.Wrapper_NgIf;
  _anchor_7:any;
  /*private*/ _vc_7:import11.ViewContainer;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import12.Wrapper_NgIf;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _NgForm_12_3:import13.Wrapper_NgForm;
  _ControlContainer_12_4:any;
  _NgControlStatusGroup_12_5:import14.Wrapper_NgControlStatusGroup;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _vc_14:import11.ViewContainer;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import12.Wrapper_NgIf;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _DefaultValueAccessor_23_3:import15.Wrapper_DefaultValueAccessor;
  _RequiredValidator_23_4:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_23_5:any[];
  _NG_VALUE_ACCESSOR_23_6:any[];
  _NgModel_23_7:import17.Wrapper_NgModel;
  _NgControl_23_8:any;
  _NgControlStatus_23_9:import14.Wrapper_NgControlStatus;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _DefaultValueAccessor_31_3:import15.Wrapper_DefaultValueAccessor;
  _RequiredValidator_31_4:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_31_5:any[];
  _NG_VALUE_ACCESSOR_31_6:any[];
  _NgModel_31_7:import17.Wrapper_NgModel;
  _NgControl_31_8:any;
  _NgControlStatus_31_9:import14.Wrapper_NgControlStatus;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _DefaultValueAccessor_42_3:import15.Wrapper_DefaultValueAccessor;
  _RequiredValidator_42_4:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_42_5:any[];
  _NG_VALUE_ACCESSOR_42_6:any[];
  _NgModel_42_7:import17.Wrapper_NgModel;
  _NgControl_42_8:any;
  _NgControlStatus_42_9:import14.Wrapper_NgControlStatus;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _anchor_55:any;
  /*private*/ _vc_55:import11.ViewContainer;
  _TemplateRef_55_5:any;
  _NgIf_55_6:import12.Wrapper_NgIf;
  _text_56:any;
  _anchor_57:any;
  /*private*/ _vc_57:import11.ViewContainer;
  _TemplateRef_57_5:any;
  _NgIf_57_6:import12.Wrapper_NgIf;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _SelectControlValueAccessor_71_3:import18.Wrapper_SelectControlValueAccessor;
  _RequiredValidator_71_4:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_71_5:any[];
  _NG_VALUE_ACCESSOR_71_6:any[];
  _NgModel_71_7:import17.Wrapper_NgModel;
  _NgControl_71_8:any;
  _NgControlStatus_71_9:import14.Wrapper_NgControlStatus;
  _text_72:any;
  _anchor_73:any;
  /*private*/ _vc_73:import11.ViewContainer;
  _TemplateRef_73_5:any;
  _NgFor_73_6:import19.Wrapper_NgFor;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _anchor_78:any;
  /*private*/ _vc_78:import11.ViewContainer;
  _TemplateRef_78_5:any;
  _NgIf_78_6:import12.Wrapper_NgIf;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  /*private*/ _expr_146:any;
  /*private*/ _expr_147:any;
  /*private*/ _expr_148:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ConfigUserComponent0,renderType_ConfigUserComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_146 = import20.UNINITIALIZED;
    this._expr_147 = import20.UNINITIALIZED;
    this._expr_148 = import20.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','page'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import11.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import21.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import12.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','title'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n        Create ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_6 = new import11.ViewContainer(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import21.TemplateRef_(this,6,this._anchor_6);
    this._NgIf_6_6 = new import12.Wrapper_NgIf(this._vc_6.vcRef,this._TemplateRef_6_5);
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_7 = new import11.ViewContainer(7,4,this,this._anchor_7);
    this._TemplateRef_7_5 = new import21.TemplateRef_(this,7,this._anchor_7);
    this._NgIf_7_6 = new import12.Wrapper_NgIf(this._vc_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText(this._el_4,' Account\n    ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','content'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_12_3 = new import13.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_12_4 = this._NgForm_12_3.context;
    this._NgControlStatusGroup_12_5 = new import14.Wrapper_NgControlStatusGroup(this._ControlContainer_12_4);
    this._text_13 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_12,(null as any));
    this._vc_14 = new import11.ViewContainer(14,12,this,this._anchor_14);
    this._TemplateRef_14_5 = new import21.TemplateRef_(this,14,this._anchor_14);
    this._NgIf_14_6 = new import12.Wrapper_NgIf(this._vc_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_12,'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','flex-item half-width left-half'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'First Name',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_18,'input',new import3.InlineArray16(10,'autofocus','','name','first','placeholder','John','required','','type','text'),(null as any));
    this._DefaultValueAccessor_23_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_23));
    this._RequiredValidator_23_4 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_23_5 = [this._RequiredValidator_23_4.context];
    this._NG_VALUE_ACCESSOR_23_6 = [this._DefaultValueAccessor_23_3.context];
    this._NgModel_23_7 = new import17.Wrapper_NgModel(this._ControlContainer_12_4,this._NG_VALIDATORS_23_5,(null as any),this._NG_VALUE_ACCESSOR_23_6);
    this._NgControl_23_8 = this._NgModel_23_7.context;
    this._NgControlStatus_23_9 = new import14.Wrapper_NgControlStatus(this._NgControl_23_8);
    this._text_24 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._text_25 = this.renderer.createText(this._el_16,'\n                 ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','flex-item half-width right-half'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Last Name',(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_26,'input',new import3.InlineArray8(8,'name','last','placeholder','Smith','required','','type','text'),(null as any));
    this._DefaultValueAccessor_31_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_31));
    this._RequiredValidator_31_4 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_31_5 = [this._RequiredValidator_31_4.context];
    this._NG_VALUE_ACCESSOR_31_6 = [this._DefaultValueAccessor_31_3.context];
    this._NgModel_31_7 = new import17.Wrapper_NgModel(this._ControlContainer_12_4,this._NG_VALIDATORS_31_5,(null as any),this._NG_VALUE_ACCESSOR_31_6);
    this._NgControl_31_8 = this._NgModel_31_7.context;
    this._NgControlStatus_31_9 = new import14.Wrapper_NgControlStatus(this._NgControl_31_8);
    this._text_32 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._text_33 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._text_34 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_12,'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'div',new import3.InlineArray2(2,'class','flex-item full-width'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'\n                    ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_37,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Email',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n                    ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_37,'input',new import3.InlineArray8(8,'name','email','placeholder','john.smith@example.com','required','','type','email'),(null as any));
    this._DefaultValueAccessor_42_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_42));
    this._RequiredValidator_42_4 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_42_5 = [this._RequiredValidator_42_4.context];
    this._NG_VALUE_ACCESSOR_42_6 = [this._DefaultValueAccessor_42_3.context];
    this._NgModel_42_7 = new import17.Wrapper_NgModel(this._ControlContainer_12_4,this._NG_VALIDATORS_42_5,(null as any),this._NG_VALUE_ACCESSOR_42_6);
    this._NgControl_42_8 = this._NgModel_42_7.context;
    this._NgControlStatus_42_9 = new import14.Wrapper_NgControlStatus(this._NgControl_42_8);
    this._text_43 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._text_44 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._text_45 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_12,'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'\n                ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'div',new import3.InlineArray2(2,'class','flex-item half-width left-half'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'\n                    ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_48,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'Password',(null as any));
    this._text_52 = this.renderer.createText(this._el_48,'\n                    ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_48,'div',new import3.InlineArray2(2,'class','input-button-wrapper'),(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'\n                        ',(null as any));
    this._anchor_55 = this.renderer.createTemplateAnchor(this._el_53,(null as any));
    this._vc_55 = new import11.ViewContainer(55,53,this,this._anchor_55);
    this._TemplateRef_55_5 = new import21.TemplateRef_(this,55,this._anchor_55);
    this._NgIf_55_6 = new import12.Wrapper_NgIf(this._vc_55.vcRef,this._TemplateRef_55_5);
    this._text_56 = this.renderer.createText(this._el_53,'\n                        ',(null as any));
    this._anchor_57 = this.renderer.createTemplateAnchor(this._el_53,(null as any));
    this._vc_57 = new import11.ViewContainer(57,53,this,this._anchor_57);
    this._TemplateRef_57_5 = new import21.TemplateRef_(this,57,this._anchor_57);
    this._NgIf_57_6 = new import12.Wrapper_NgIf(this._vc_57.vcRef,this._TemplateRef_57_5);
    this._text_58 = this.renderer.createText(this._el_53,'\n                        ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_53,'div',new import3.InlineArray2(2,'class','input-button-button'),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'\n                            ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_59,'img',new import3.InlineArray4(4,'class','input-button-img','src','./src/eye.svg'),(null as any));
    this._text_62 = this.renderer.createText(this._el_59,'\n                        ',(null as any));
    this._text_63 = this.renderer.createText(this._el_53,'\n                    ',(null as any));
    this._text_64 = this.renderer.createText(this._el_48,'\n                ',(null as any));
    this._text_65 = this.renderer.createText(this._el_46,'\n                ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_46,'div',new import3.InlineArray2(2,'class','flex-item half-width right-half'),(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'\n                    ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_66,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'Timezone',(null as any));
    this._text_70 = this.renderer.createText(this._el_66,'\n                    ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_66,'select',new import3.InlineArray4(4,'name','timezone','required',''),(null as any));
    this._SelectControlValueAccessor_71_3 = new import18.Wrapper_SelectControlValueAccessor(this.renderer,new import22.ElementRef(this._el_71));
    this._RequiredValidator_71_4 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_71_5 = [this._RequiredValidator_71_4.context];
    this._NG_VALUE_ACCESSOR_71_6 = [this._SelectControlValueAccessor_71_3.context];
    this._NgModel_71_7 = new import17.Wrapper_NgModel(this._ControlContainer_12_4,this._NG_VALIDATORS_71_5,(null as any),this._NG_VALUE_ACCESSOR_71_6);
    this._NgControl_71_8 = this._NgModel_71_7.context;
    this._NgControlStatus_71_9 = new import14.Wrapper_NgControlStatus(this._NgControl_71_8);
    this._text_72 = this.renderer.createText(this._el_71,'\n                        ',(null as any));
    this._anchor_73 = this.renderer.createTemplateAnchor(this._el_71,(null as any));
    this._vc_73 = new import11.ViewContainer(73,71,this,this._anchor_73);
    this._TemplateRef_73_5 = new import21.TemplateRef_(this,73,this._anchor_73);
    this._NgFor_73_6 = new import19.Wrapper_NgFor(this._vc_73.vcRef,this._TemplateRef_73_5,this.parentView.injectorGet(import23.IterableDiffers,this.parentIndex),this.ref);
    this._text_74 = this.renderer.createText(this._el_71,'\n                    ',(null as any));
    this._text_75 = this.renderer.createText(this._el_66,'\n                ',(null as any));
    this._text_76 = this.renderer.createText(this._el_46,'\n            ',(null as any));
    this._text_77 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._anchor_78 = this.renderer.createTemplateAnchor(this._el_12,(null as any));
    this._vc_78 = new import11.ViewContainer(78,12,this,this._anchor_78);
    this._TemplateRef_78_5 = new import21.TemplateRef_(this,78,this._anchor_78);
    this._NgIf_78_6 = new import12.Wrapper_NgIf(this._vc_78.vcRef,this._TemplateRef_78_5);
    this._text_79 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_12,'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_81 = this.renderer.createText(this._el_80,'\n                ',(null as any));
    this._el_82 = import3.createRenderElement(this.renderer,this._el_80,'div',new import3.InlineArray2(2,'class','flex-item next'),(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'\n                    ',(null as any));
    this._el_84 = import3.createRenderElement(this.renderer,this._el_82,'button',new import3.InlineArray4(4,'class','nextBtn','type','submit'),(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'Continue',(null as any));
    this._text_86 = this.renderer.createText(this._el_82,'\n                ',(null as any));
    this._text_87 = this.renderer.createText(this._el_80,'\n            ',(null as any));
    this._text_88 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._text_89 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._text_90 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_12));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_23));
    this._NgModel_23_7.subscribe(this,this.eventHandler(this.handleEvent_23),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_31,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_31));
    this._NgModel_31_7.subscribe(this,this.eventHandler(this.handleEvent_31),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_42,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_42));
    this._NgModel_42_7.subscribe(this,this.eventHandler(this.handleEvent_42),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_59,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_59));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_71,new import3.InlineArray8(8,'ngModelChange',(null as any),'click',(null as any),'blur',(null as any),'change',(null as any)),this.eventHandler(this.handleEvent_71));
    this._NgModel_71_7.subscribe(this,this.eventHandler(this.handleEvent_71),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._anchor_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._anchor_55,
      this._text_56,
      this._anchor_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._anchor_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._anchor_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._text_90
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import24.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import21.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import24.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6.context; }
    if (((token === import21.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import24.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6.context; }
    if (((token === import21.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import24.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6.context; }
    if (((token === import25.DefaultValueAccessor) && (23 === requestNodeIndex))) { return this._DefaultValueAccessor_23_3.context; }
    if (((token === import26.RequiredValidator) && (23 === requestNodeIndex))) { return this._RequiredValidator_23_4.context; }
    if (((token === import27.NG_VALIDATORS) && (23 === requestNodeIndex))) { return this._NG_VALIDATORS_23_5; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (23 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_23_6; }
    if (((token === import29.NgModel) && (23 === requestNodeIndex))) { return this._NgModel_23_7.context; }
    if (((token === import30.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_8; }
    if (((token === import31.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_9.context; }
    if (((token === import25.DefaultValueAccessor) && (31 === requestNodeIndex))) { return this._DefaultValueAccessor_31_3.context; }
    if (((token === import26.RequiredValidator) && (31 === requestNodeIndex))) { return this._RequiredValidator_31_4.context; }
    if (((token === import27.NG_VALIDATORS) && (31 === requestNodeIndex))) { return this._NG_VALIDATORS_31_5; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (31 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_31_6; }
    if (((token === import29.NgModel) && (31 === requestNodeIndex))) { return this._NgModel_31_7.context; }
    if (((token === import30.NgControl) && (31 === requestNodeIndex))) { return this._NgControl_31_8; }
    if (((token === import31.NgControlStatus) && (31 === requestNodeIndex))) { return this._NgControlStatus_31_9.context; }
    if (((token === import25.DefaultValueAccessor) && (42 === requestNodeIndex))) { return this._DefaultValueAccessor_42_3.context; }
    if (((token === import26.RequiredValidator) && (42 === requestNodeIndex))) { return this._RequiredValidator_42_4.context; }
    if (((token === import27.NG_VALIDATORS) && (42 === requestNodeIndex))) { return this._NG_VALIDATORS_42_5; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (42 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_42_6; }
    if (((token === import29.NgModel) && (42 === requestNodeIndex))) { return this._NgModel_42_7.context; }
    if (((token === import30.NgControl) && (42 === requestNodeIndex))) { return this._NgControl_42_8; }
    if (((token === import31.NgControlStatus) && (42 === requestNodeIndex))) { return this._NgControlStatus_42_9.context; }
    if (((token === import21.TemplateRef) && (55 === requestNodeIndex))) { return this._TemplateRef_55_5; }
    if (((token === import24.NgIf) && (55 === requestNodeIndex))) { return this._NgIf_55_6.context; }
    if (((token === import21.TemplateRef) && (57 === requestNodeIndex))) { return this._TemplateRef_57_5; }
    if (((token === import24.NgIf) && (57 === requestNodeIndex))) { return this._NgIf_57_6.context; }
    if (((token === import21.TemplateRef) && (73 === requestNodeIndex))) { return this._TemplateRef_73_5; }
    if (((token === import32.NgFor) && (73 === requestNodeIndex))) { return this._NgFor_73_6.context; }
    if (((token === import33.SelectControlValueAccessor) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._SelectControlValueAccessor_71_3.context; }
    if (((token === import26.RequiredValidator) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._RequiredValidator_71_4.context; }
    if (((token === import27.NG_VALIDATORS) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._NG_VALIDATORS_71_5; }
    if (((token === import28.NG_VALUE_ACCESSOR) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._NG_VALUE_ACCESSOR_71_6; }
    if (((token === import29.NgModel) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._NgModel_71_7.context; }
    if (((token === import30.NgControl) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._NgControl_71_8; }
    if (((token === import31.NgControlStatus) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._NgControlStatus_71_9.context; }
    if (((token === import21.TemplateRef) && (78 === requestNodeIndex))) { return this._TemplateRef_78_5; }
    if (((token === import24.NgIf) && (78 === requestNodeIndex))) { return this._NgIf_78_6.context; }
    if (((token === import34.NgForm) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 88)))) { return this._NgForm_12_3.context; }
    if (((token === import35.ControlContainer) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 88)))) { return this._ControlContainer_12_4; }
    if (((token === import31.NgControlStatusGroup) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 88)))) { return this._NgControlStatusGroup_12_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.configService.isWizard;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    const currVal_6_0_0:any = this.context.configService.values.user.admin;
    this._NgIf_6_6.check_ngIf(currVal_6_0_0,throwOnChange,false);
    this._NgIf_6_6.ngDoCheck(this,this._anchor_6,throwOnChange);
    const currVal_7_0_0:boolean = !this.context.configService.values.user.admin;
    this._NgIf_7_6.check_ngIf(currVal_7_0_0,throwOnChange,false);
    this._NgIf_7_6.ngDoCheck(this,this._anchor_7,throwOnChange);
    this._NgForm_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    this._NgControlStatusGroup_12_5.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_14_0_0:boolean = !this.context.configService.config['user'].success;
    this._NgIf_14_6.check_ngIf(currVal_14_0_0,throwOnChange,false);
    this._NgIf_14_6.ngDoCheck(this,this._anchor_14,throwOnChange);
    this._DefaultValueAccessor_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_1_0:any = '';
    this._RequiredValidator_23_4.check_required(currVal_23_1_0,throwOnChange,false);
    this._RequiredValidator_23_4.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_2_0:any = 'first';
    this._NgModel_23_7.check_name(currVal_23_2_0,throwOnChange,false);
    const currVal_23_2_1:any = this.context.configService.values.user.name.first;
    this._NgModel_23_7.check_model(currVal_23_2_1,throwOnChange,false);
    this._NgModel_23_7.ngDoCheck(this,this._el_23,throwOnChange);
    this._NgControlStatus_23_9.ngDoCheck(this,this._el_23,throwOnChange);
    this._DefaultValueAccessor_31_3.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_31_1_0:any = '';
    this._RequiredValidator_31_4.check_required(currVal_31_1_0,throwOnChange,false);
    this._RequiredValidator_31_4.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_31_2_0:any = 'last';
    this._NgModel_31_7.check_name(currVal_31_2_0,throwOnChange,false);
    const currVal_31_2_1:any = this.context.configService.values.user.name.last;
    this._NgModel_31_7.check_model(currVal_31_2_1,throwOnChange,false);
    this._NgModel_31_7.ngDoCheck(this,this._el_31,throwOnChange);
    this._NgControlStatus_31_9.ngDoCheck(this,this._el_31,throwOnChange);
    this._DefaultValueAccessor_42_3.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_42_1_0:any = '';
    this._RequiredValidator_42_4.check_required(currVal_42_1_0,throwOnChange,false);
    this._RequiredValidator_42_4.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_42_2_0:any = 'email';
    this._NgModel_42_7.check_name(currVal_42_2_0,throwOnChange,false);
    const currVal_42_2_1:any = this.context.configService.values.user.email;
    this._NgModel_42_7.check_model(currVal_42_2_1,throwOnChange,false);
    this._NgModel_42_7.ngDoCheck(this,this._el_42,throwOnChange);
    this._NgControlStatus_42_9.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_55_0_0:any = this.context.isPasswordMasked;
    this._NgIf_55_6.check_ngIf(currVal_55_0_0,throwOnChange,false);
    this._NgIf_55_6.ngDoCheck(this,this._anchor_55,throwOnChange);
    const currVal_57_0_0:boolean = !this.context.isPasswordMasked;
    this._NgIf_57_6.check_ngIf(currVal_57_0_0,throwOnChange,false);
    this._NgIf_57_6.ngDoCheck(this,this._anchor_57,throwOnChange);
    this._SelectControlValueAccessor_71_3.ngDoCheck(this,this._el_71,throwOnChange);
    const currVal_71_1_0:any = '';
    this._RequiredValidator_71_4.check_required(currVal_71_1_0,throwOnChange,false);
    this._RequiredValidator_71_4.ngDoCheck(this,this._el_71,throwOnChange);
    const currVal_71_2_0:any = 'timezone';
    this._NgModel_71_7.check_name(currVal_71_2_0,throwOnChange,false);
    const currVal_71_2_1:any = this.context.configService.values.user.timezone;
    this._NgModel_71_7.check_model(currVal_71_2_1,throwOnChange,false);
    this._NgModel_71_7.ngDoCheck(this,this._el_71,throwOnChange);
    this._NgControlStatus_71_9.ngDoCheck(this,this._el_71,throwOnChange);
    const currVal_73_0_0:any = this.context.configService.timezones;
    this._NgFor_73_6.check_ngForOf(currVal_73_0_0,throwOnChange,false);
    this._NgFor_73_6.ngDoCheck(this,this._anchor_73,throwOnChange);
    const currVal_78_0_0:boolean = !this.context.configService.isWizard;
    this._NgIf_78_6.check_ngIf(currVal_78_0_0,throwOnChange,false);
    this._NgIf_78_6.ngDoCheck(this,this._anchor_78,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_6.detectChangesInNestedViews(throwOnChange);
    this._vc_7.detectChangesInNestedViews(throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    this._vc_55.detectChangesInNestedViews(throwOnChange);
    this._vc_57.detectChangesInNestedViews(throwOnChange);
    this._vc_73.detectChangesInNestedViews(throwOnChange);
    this._vc_78.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_12_5.checkHost(this,this,this._el_12,throwOnChange);
    this._RequiredValidator_23_4.checkHost(this,this,this._el_23,throwOnChange);
    this._NgControlStatus_23_9.checkHost(this,this,this._el_23,throwOnChange);
    this._RequiredValidator_31_4.checkHost(this,this,this._el_31,throwOnChange);
    this._NgControlStatus_31_9.checkHost(this,this,this._el_31,throwOnChange);
    this._RequiredValidator_42_4.checkHost(this,this,this._el_42,throwOnChange);
    this._NgControlStatus_42_9.checkHost(this,this,this._el_42,throwOnChange);
    const currVal_146:any = this.context.isPasswordFocused;
    if (import3.checkBinding(throwOnChange,this._expr_146,currVal_146)) {
      this.renderer.setElementClass(this._el_53,'input-button-wrapper-focus',currVal_146);
      this._expr_146 = currVal_146;
    }
    const currVal_147:any = this.context.isPasswordMasked;
    if (import3.checkBinding(throwOnChange,this._expr_147,currVal_147)) {
      this.renderer.setElementClass(this._el_61,'input-button-img-password-masked',currVal_147);
      this._expr_147 = currVal_147;
    }
    const currVal_148:any = this.context.isSelectOpened;
    if (import3.checkBinding(throwOnChange,this._expr_148,currVal_148)) {
      this.renderer.setElementClass(this._el_71,'select-opened',currVal_148);
      this._expr_148 = currVal_148;
    }
    this._RequiredValidator_71_4.checkHost(this,this,this._el_71,throwOnChange);
    this._NgControlStatus_71_9.checkHost(this,this,this._el_71,throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_6.destroyNestedViews();
    this._vc_7.destroyNestedViews();
    this._vc_14.destroyNestedViews();
    this._vc_55.destroyNestedViews();
    this._vc_57.destroyNestedViews();
    this._vc_73.destroyNestedViews();
    this._vc_78.destroyNestedViews();
    this._NgModel_23_7.ngOnDestroy();
    this._NgModel_31_7.ngOnDestroy();
    this._NgModel_42_7.ngOnDestroy();
    this._NgModel_71_7.ngOnDestroy();
    this._NgForm_12_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_ConfigUserComponent1(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 6)) { return new View_ConfigUserComponent2(this.viewUtils,this,6,this._anchor_6,this._vc_6); }
    if ((nodeIndex == 7)) { return new View_ConfigUserComponent3(this.viewUtils,this,7,this._anchor_7,this._vc_7); }
    if ((nodeIndex == 14)) { return new View_ConfigUserComponent4(this.viewUtils,this,14,this._anchor_14,this._vc_14); }
    if ((nodeIndex == 55)) { return new View_ConfigUserComponent5(this.viewUtils,this,55,this._anchor_55,this._vc_55); }
    if ((nodeIndex == 57)) { return new View_ConfigUserComponent6(this.viewUtils,this,57,this._anchor_57,this._vc_57); }
    if ((nodeIndex == 73)) { return new View_ConfigUserComponent7(this.viewUtils,this,73,this._anchor_73,this._vc_73); }
    if ((nodeIndex == 78)) { return new View_ConfigUserComponent8(this.viewUtils,this,78,this._anchor_78,this._vc_78); }
    return (null as any);
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_12_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'submit')) {
      const pd_sub_0:any = ((<any>this.context.doSubmit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_23_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.configService.values.user.name.first = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_31(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_31_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.configService.values.user.name.last = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_42(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_42_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.configService.values.user.email = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_59(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.isPasswordMasked = !this.context.isPasswordMasked)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_71(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_71_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.configService.values.user.timezone = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'click')) {
      const pd_sub_1:any = ((<any>(this.context.isSelectOpened = !this.context.isSelectOpened)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'blur')) {
      const pd_sub_2:any = ((<any>(this.context.isSelectOpened = false)) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
}
class View_ConfigUserComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ConfigUserComponent1,renderType_ConfigUserComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','step'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Step 1 of 4\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ConfigUserComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ConfigUserComponent2,renderType_ConfigUserComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Administrator',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ConfigUserComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ConfigUserComponent3,renderType_ConfigUserComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'User',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ConfigUserComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ConfigUserComponent4,renderType_ConfigUserComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_5 = import20.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','flex-item full-width error'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5:any = import3.inlineInterpolate(1,'\n                    ',this.parentView.context.configService.config['user'].error,'\n                ');
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ConfigUserComponent5 extends import1.AppView<any> {
  _el_0:any;
  _DefaultValueAccessor_0_3:import15.Wrapper_DefaultValueAccessor;
  _RequiredValidator_0_4:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_0_5:any[];
  _NG_VALUE_ACCESSOR_0_6:any[];
  _NgModel_0_7:import17.Wrapper_NgModel;
  _NgControl_0_8:any;
  _NgControlStatus_0_9:import14.Wrapper_NgControlStatus;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ConfigUserComponent5,renderType_ConfigUserComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray16(10,'class','input-button-input','name','password','placeholder','••••••••••','required','','type','password'),(null as any));
    this._DefaultValueAccessor_0_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_0));
    this._RequiredValidator_0_4 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_0_5 = [this._RequiredValidator_0_4.context];
    this._NG_VALUE_ACCESSOR_0_6 = [this._DefaultValueAccessor_0_3.context];
    this._NgModel_0_7 = new import17.Wrapper_NgModel((<View_ConfigUserComponent0>this.parentView)._ControlContainer_12_4,this._NG_VALIDATORS_0_5,(null as any),this._NG_VALUE_ACCESSOR_0_6);
    this._NgControl_0_8 = this._NgModel_0_7.context;
    this._NgControlStatus_0_9 = new import14.Wrapper_NgControlStatus(this._NgControl_0_8);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(8,'ngModelChange',(null as any),'focus',(null as any),'blur',(null as any),'input',(null as any)),this.eventHandler(this.handleEvent_0));
    this._NgModel_0_7.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.DefaultValueAccessor) && (0 === requestNodeIndex))) { return this._DefaultValueAccessor_0_3.context; }
    if (((token === import26.RequiredValidator) && (0 === requestNodeIndex))) { return this._RequiredValidator_0_4.context; }
    if (((token === import27.NG_VALIDATORS) && (0 === requestNodeIndex))) { return this._NG_VALIDATORS_0_5; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_6; }
    if (((token === import29.NgModel) && (0 === requestNodeIndex))) { return this._NgModel_0_7.context; }
    if (((token === import30.NgControl) && (0 === requestNodeIndex))) { return this._NgControl_0_8; }
    if (((token === import31.NgControlStatus) && (0 === requestNodeIndex))) { return this._NgControlStatus_0_9.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = '';
    this._RequiredValidator_0_4.check_required(currVal_0_1_0,throwOnChange,false);
    this._RequiredValidator_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_2_0:any = 'password';
    this._NgModel_0_7.check_name(currVal_0_2_0,throwOnChange,false);
    const currVal_0_2_1:any = this.parentView.context.configService.values.user.password;
    this._NgModel_0_7.check_model(currVal_0_2_1,throwOnChange,false);
    this._NgModel_0_7.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatus_0_9.ngDoCheck(this,this._el_0,throwOnChange);
    this._RequiredValidator_0_4.checkHost(this,this,this._el_0,throwOnChange);
    this._NgControlStatus_0_9.checkHost(this,this,this._el_0,throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_0_7.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.configService.values.user.password = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'focus')) {
      const pd_sub_1:any = ((<any>(this.parentView.context.isPasswordFocused = true)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'blur')) {
      const pd_sub_2:any = ((<any>(this.parentView.context.isPasswordFocused = false)) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
}
class View_ConfigUserComponent6 extends import1.AppView<any> {
  _el_0:any;
  _DefaultValueAccessor_0_3:import15.Wrapper_DefaultValueAccessor;
  _RequiredValidator_0_4:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_0_5:any[];
  _NG_VALUE_ACCESSOR_0_6:any[];
  _NgModel_0_7:import17.Wrapper_NgModel;
  _NgControl_0_8:any;
  _NgControlStatus_0_9:import14.Wrapper_NgControlStatus;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ConfigUserComponent6,renderType_ConfigUserComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray16(10,'class','input-button-input','name','passwordText','placeholder','••••••••••','required','','type','text'),(null as any));
    this._DefaultValueAccessor_0_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_0));
    this._RequiredValidator_0_4 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_0_5 = [this._RequiredValidator_0_4.context];
    this._NG_VALUE_ACCESSOR_0_6 = [this._DefaultValueAccessor_0_3.context];
    this._NgModel_0_7 = new import17.Wrapper_NgModel((<View_ConfigUserComponent0>this.parentView)._ControlContainer_12_4,this._NG_VALIDATORS_0_5,(null as any),this._NG_VALUE_ACCESSOR_0_6);
    this._NgControl_0_8 = this._NgModel_0_7.context;
    this._NgControlStatus_0_9 = new import14.Wrapper_NgControlStatus(this._NgControl_0_8);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(8,'ngModelChange',(null as any),'focus',(null as any),'blur',(null as any),'input',(null as any)),this.eventHandler(this.handleEvent_0));
    this._NgModel_0_7.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.DefaultValueAccessor) && (0 === requestNodeIndex))) { return this._DefaultValueAccessor_0_3.context; }
    if (((token === import26.RequiredValidator) && (0 === requestNodeIndex))) { return this._RequiredValidator_0_4.context; }
    if (((token === import27.NG_VALIDATORS) && (0 === requestNodeIndex))) { return this._NG_VALIDATORS_0_5; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_6; }
    if (((token === import29.NgModel) && (0 === requestNodeIndex))) { return this._NgModel_0_7.context; }
    if (((token === import30.NgControl) && (0 === requestNodeIndex))) { return this._NgControl_0_8; }
    if (((token === import31.NgControlStatus) && (0 === requestNodeIndex))) { return this._NgControlStatus_0_9.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = '';
    this._RequiredValidator_0_4.check_required(currVal_0_1_0,throwOnChange,false);
    this._RequiredValidator_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_2_0:any = 'passwordText';
    this._NgModel_0_7.check_name(currVal_0_2_0,throwOnChange,false);
    const currVal_0_2_1:any = this.parentView.context.configService.values.user.password;
    this._NgModel_0_7.check_model(currVal_0_2_1,throwOnChange,false);
    this._NgModel_0_7.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatus_0_9.ngDoCheck(this,this._el_0,throwOnChange);
    this._RequiredValidator_0_4.checkHost(this,this,this._el_0,throwOnChange);
    this._NgControlStatus_0_9.checkHost(this,this,this._el_0,throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_0_7.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.configService.values.user.password = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'focus')) {
      const pd_sub_1:any = ((<any>(this.parentView.context.isPasswordFocused = true)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'blur')) {
      const pd_sub_2:any = ((<any>(this.parentView.context.isPasswordFocused = false)) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
}
class View_ConfigUserComponent7 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import18.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_0_4:import36.Wrapper_NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ConfigUserComponent7,renderType_ConfigUserComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import20.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_0_3 = new import18.Wrapper_NgSelectOption(new import22.ElementRef(this._el_0),this.renderer,(<View_ConfigUserComponent0>this.parentView)._SelectControlValueAccessor_71_3.context);
    this._NgSelectMultipleOption_0_4 = new import36.Wrapper_NgSelectMultipleOption(new import22.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3.context; }
    if (((token === import37.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.$implicit;
    this._NgSelectOption_0_3.check_value(currVal_0_0_0,throwOnChange,false);
    this._NgSelectOption_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = this.context.$implicit;
    this._NgSelectMultipleOption_0_4.check_value(currVal_0_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_4:any = import3.inlineInterpolate(1,'',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ConfigUserComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _CheckboxControlValueAccessor_7_3:import38.Wrapper_CheckboxControlValueAccessor;
  _NG_VALUE_ACCESSOR_7_4:any[];
  _NgModel_7_5:import17.Wrapper_NgModel;
  _NgControl_7_6:any;
  _NgControlStatus_7_7:import14.Wrapper_NgControlStatus;
  _text_8:any;
  _text_9:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ConfigUserComponent8,renderType_ConfigUserComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','flex-item full-width'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Administrator',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'input',new import3.InlineArray4(4,'name','admin','type','checkbox'),(null as any));
    this._CheckboxControlValueAccessor_7_3 = new import38.Wrapper_CheckboxControlValueAccessor(this.renderer,new import22.ElementRef(this._el_7));
    this._NG_VALUE_ACCESSOR_7_4 = [this._CheckboxControlValueAccessor_7_3.context];
    this._NgModel_7_5 = new import17.Wrapper_NgModel((<View_ConfigUserComponent0>this.parentView)._ControlContainer_12_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_7_4);
    this._NgControl_7_6 = this._NgModel_7_5.context;
    this._NgControlStatus_7_7 = new import14.Wrapper_NgControlStatus(this._NgControl_7_6);
    this._text_8 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray8(6,'ngModelChange',(null as any),'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_7));
    this._NgModel_7_5.subscribe(this,this.eventHandler(this.handleEvent_7),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import39.CheckboxControlValueAccessor) && (7 === requestNodeIndex))) { return this._CheckboxControlValueAccessor_7_3.context; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (7 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_7_4; }
    if (((token === import29.NgModel) && (7 === requestNodeIndex))) { return this._NgModel_7_5.context; }
    if (((token === import30.NgControl) && (7 === requestNodeIndex))) { return this._NgControl_7_6; }
    if (((token === import31.NgControlStatus) && (7 === requestNodeIndex))) { return this._NgControlStatus_7_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CheckboxControlValueAccessor_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    const currVal_7_1_0:any = 'admin';
    this._NgModel_7_5.check_name(currVal_7_1_0,throwOnChange,false);
    const currVal_7_1_1:any = this.parentView.context.configService.values.user.admin;
    this._NgModel_7_5.check_model(currVal_7_1_1,throwOnChange,false);
    this._NgModel_7_5.ngDoCheck(this,this._el_7,throwOnChange);
    this._NgControlStatus_7_7.ngDoCheck(this,this._el_7,throwOnChange);
    this._NgControlStatus_7_7.checkHost(this,this,this._el_7,throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_7_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._CheckboxControlValueAccessor_7_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.configService.values.user.admin = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}