/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app/config/config.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/router/src/router_module';
import * as import4 from '@angular/common/src/localization';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from './config-base/config-base.component.ngfactory';
import * as import7 from '../../../../src/app/config/config-base/config-base.component';
import * as import8 from '@angular/core/src/i18n/tokens';
import * as import9 from '@angular/router/src/router_config_loader';
class ConfigModuleInjector extends import0.NgModuleInjector<import1.ConfigModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _ConfigModule_2:import1.ConfigModule;
  __LOCALE_ID_3:any;
  __NgLocalization_4:import4.NgLocaleLocalization;
  __ROUTES_5:any[];
  constructor(parent:import5.Injector) {
    super(parent,[import6.ConfigBaseComponentNgFactory],([] as any[]));
  }
  get _LOCALE_ID_3():any {
    if ((this.__LOCALE_ID_3 == null)) { (this.__LOCALE_ID_3 = 'en-US'); }
    return this.__LOCALE_ID_3;
  }
  get _NgLocalization_4():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import4.NgLocaleLocalization(this._LOCALE_ID_3)); }
    return this.__NgLocalization_4;
  }
  get _ROUTES_5():any[] {
        if ((this.__ROUTES_5 == null)) { (this.__ROUTES_5 = [[{
          path: 'config',
          component: import7.ConfigBaseComponent
        }
    ]]); }
    return this.__ROUTES_5;
  }
  createInternal():import1.ConfigModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ROUTER_FORROOT_GUARD,(null as any)));
    this._ConfigModule_2 = new import1.ConfigModule();
    return this._ConfigModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import1.ConfigModule)) { return this._ConfigModule_2; }
    if ((token === import8.LOCALE_ID)) { return this._LOCALE_ID_3; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import9.ROUTES)) { return this._ROUTES_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ConfigModuleNgFactory:import0.NgModuleFactory<import1.ConfigModule> = new import0.NgModuleFactory(ConfigModuleInjector,import1.ConfigModule);