/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app/auth/auth.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/common/src/common_module';
import * as import4 from '@angular/forms/src/directives';
import * as import5 from '@angular/forms/src/form_providers';
import * as import6 from '@angular/common/src/localization';
import * as import7 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import8 from '@angular/core/src/di/injector';
import * as import9 from './auth-login/auth-login.component.ngfactory';
import * as import10 from '../../../../src/app/auth/auth-login/auth-login.component';
import * as import11 from '@angular/core/src/i18n/tokens';
import * as import12 from '@angular/router/src/router_config_loader';
class AuthModuleInjector extends import0.NgModuleInjector<import1.AuthModule> {
  _RouterModule_0:import2.RouterModule;
  _CommonModule_1:import3.CommonModule;
  _InternalFormsSharedModule_2:import4.InternalFormsSharedModule;
  _FormsModule_3:import5.FormsModule;
  _AuthModule_4:import1.AuthModule;
  __LOCALE_ID_5:any;
  __NgLocalization_6:import6.NgLocaleLocalization;
  __RadioControlRegistry_7:import7.RadioControlRegistry;
  __ROUTES_8:any[];
  constructor(parent:import8.Injector) {
    super(parent,[import9.AuthLoginComponentNgFactory],([] as any[]));
  }
  get _LOCALE_ID_5():any {
    if ((this.__LOCALE_ID_5 == null)) { (this.__LOCALE_ID_5 = 'en-US'); }
    return this.__LOCALE_ID_5;
  }
  get _NgLocalization_6():import6.NgLocaleLocalization {
    if ((this.__NgLocalization_6 == null)) { (this.__NgLocalization_6 = new import6.NgLocaleLocalization(this._LOCALE_ID_5)); }
    return this.__NgLocalization_6;
  }
  get _RadioControlRegistry_7():import7.RadioControlRegistry {
    if ((this.__RadioControlRegistry_7 == null)) { (this.__RadioControlRegistry_7 = new import7.RadioControlRegistry()); }
    return this.__RadioControlRegistry_7;
  }
  get _ROUTES_8():any[] {
        if ((this.__ROUTES_8 == null)) { (this.__ROUTES_8 = [[{
            children: [{
              component: import10.AuthLoginComponent,
              path: 'login'
            }
          ],
          path: 'auth'
        }
    ]]); }
    return this.__ROUTES_8;
  }
  createInternal():import1.AuthModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._CommonModule_1 = new import3.CommonModule();
    this._InternalFormsSharedModule_2 = new import4.InternalFormsSharedModule();
    this._FormsModule_3 = new import5.FormsModule();
    this._AuthModule_4 = new import1.AuthModule();
    return this._AuthModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.CommonModule)) { return this._CommonModule_1; }
    if ((token === import4.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_2; }
    if ((token === import5.FormsModule)) { return this._FormsModule_3; }
    if ((token === import1.AuthModule)) { return this._AuthModule_4; }
    if ((token === import11.LOCALE_ID)) { return this._LOCALE_ID_5; }
    if ((token === import6.NgLocalization)) { return this._NgLocalization_6; }
    if ((token === import7.RadioControlRegistry)) { return this._RadioControlRegistry_7; }
    if ((token === import12.ROUTES)) { return this._ROUTES_8; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AuthModuleNgFactory:import0.NgModuleFactory<import1.AuthModule> = new import0.NgModuleFactory(AuthModuleInjector,import1.AuthModule);