'use strict';

const config = {
    port: process.env.PORT || 3000,
    ip: process.env.IP || '0.0.0.0',

    // MongoDB connection string. For example, '127.0.0.1:27017/davis'
    database: {
        dsn: '<mongodb_database_dsn>'
    },

    // Currently only US english is supported
    lang: 'en-us',

    // The dynatrace URL and token
    // More information can be found here: https://help.dynatrace.com/api-documentation/v1/
    dynatrace: {
        url: '<tenant_url>',
        token: '<dynatrace_token>',
        // Optional - Set to false when using self signed certs
        strictSSL: true
    },

    //
    nlp: {
        wit: '<wit_token>'
    },

    // Watson STT and TTS is only needed for the WebUI
    watson: {
        enabled: true,
        stt: {
            user: '<watson_stt_user_name>',
            password: '<watson_stt_password>'
        },
        tts: {
            user: '<watson_tts_user_name>',
            password: '<watson_tts_password>'
        }
    },

    // The Slack bot token can be created on the apps and integrations page
    slack: {
        enabled: true,
        key: '<slack_token>',
        notifications: {
            alerts: {
                enabled: true,
                channels: [
                    {
                        name: '<slack_channel_name>',
                        state: ['open', 'resolved'],
                        impact: ['application', 'service', 'infrastructure'],
                        tags: {
                            includes: [],
                            excludes: []
                        }
                    }
                ]
            }
        }
    },

    // The Alexa ID is generated by Amazon when you configure your Alexa app.
    alexa: [{
        id: '<alexa_token>',
        name: {
            first: '<first_name>',
            last: '<last_name>'
        },
        timezone: 'America/Detroit'
    }]
};

config.aliases = require('./aliases');

module.exports = config;