/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/config/config-dynatrace/config-dynatrace.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../src/app/config/config.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from './config-dynatrace.component.css.shim';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import13 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import14 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import16 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import17 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/common/src/directives/ng_if';
import * as import21 from '@angular/forms/src/directives/default_value_accessor';
import * as import22 from '@angular/forms/src/directives/validators';
import * as import23 from '@angular/forms/src/validators';
import * as import24 from '@angular/forms/src/directives/control_value_accessor';
import * as import25 from '@angular/forms/src/directives/ng_model';
import * as import26 from '@angular/forms/src/directives/ng_control';
import * as import27 from '@angular/forms/src/directives/ng_control_status';
import * as import28 from '@angular/forms/src/directives/ng_form';
import * as import29 from '@angular/forms/src/directives/control_container';
import * as import30 from '@angular/core/src/change_detection/change_detection_util';
export class Wrapper_ConfigDynatraceComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ConfigDynatraceComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.ConfigDynatraceComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ConfigDynatraceComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ConfigDynatraceComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ConfigDynatraceComponent>;
  _ConfigDynatraceComponent_0_3:Wrapper_ConfigDynatraceComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ConfigDynatraceComponent_Host0,renderType_ConfigDynatraceComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'config-dynatrace',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ConfigDynatraceComponent0(this.viewUtils,this,0,this._el_0);
    this._ConfigDynatraceComponent_0_3 = new Wrapper_ConfigDynatraceComponent(this.injectorGet(import8.ConfigService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex));
    this.compView_0.create(this._ConfigDynatraceComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ConfigDynatraceComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ConfigDynatraceComponent) && (0 === requestNodeIndex))) { return this._ConfigDynatraceComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ConfigDynatraceComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ConfigDynatraceComponentNgFactory:import7.ComponentFactory<import0.ConfigDynatraceComponent> = new import7.ComponentFactory<import0.ConfigDynatraceComponent>('config-dynatrace',View_ConfigDynatraceComponent_Host0,import0.ConfigDynatraceComponent);
const styles_ConfigDynatraceComponent:any[] = [import10.styles];
var renderType_ConfigDynatraceComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_ConfigDynatraceComponent,{});
export class View_ConfigDynatraceComponent0 extends import1.AppView<import0.ConfigDynatraceComponent> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import11.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import12.Wrapper_NgIf;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _NgForm_9_3:import13.Wrapper_NgForm;
  _ControlContainer_9_4:any;
  _NgControlStatusGroup_9_5:import14.Wrapper_NgControlStatusGroup;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _vc_11:import11.ViewContainer;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import12.Wrapper_NgIf;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _DefaultValueAccessor_20_3:import15.Wrapper_DefaultValueAccessor;
  _RequiredValidator_20_4:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_20_5:any[];
  _NG_VALUE_ACCESSOR_20_6:any[];
  _NgModel_20_7:import17.Wrapper_NgModel;
  _NgControl_20_8:any;
  _NgControlStatus_20_9:import14.Wrapper_NgControlStatus;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _DefaultValueAccessor_31_3:import15.Wrapper_DefaultValueAccessor;
  _RequiredValidator_31_4:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_31_5:any[];
  _NG_VALUE_ACCESSOR_31_6:any[];
  _NgModel_31_7:import17.Wrapper_NgModel;
  _NgControl_31_8:any;
  _NgControlStatus_31_9:import14.Wrapper_NgControlStatus;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ConfigDynatraceComponent0,renderType_ConfigDynatraceComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','page'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import11.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import18.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import12.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','title'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n        Connect to Dynatrace\n    ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','content'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_9_3 = new import13.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_9_4 = this._NgForm_9_3.context;
    this._NgControlStatusGroup_9_5 = new import14.Wrapper_NgControlStatusGroup(this._ControlContainer_9_4);
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._vc_11 = new import11.ViewContainer(11,9,this,this._anchor_11);
    this._TemplateRef_11_5 = new import18.TemplateRef_(this,11,this._anchor_11);
    this._NgIf_11_6 = new import12.Wrapper_NgIf(this._vc_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_9,'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','flex-item full-width'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Dynatrace Tenant URL',(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_15,'input',new import3.InlineArray16(10,'autofocus','','name','url','placeholder','https://qwefgmasd.live.dynatrace.com','required','','type','text'),(null as any));
    this._DefaultValueAccessor_20_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_20));
    this._RequiredValidator_20_4 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_20_5 = [this._RequiredValidator_20_4.context];
    this._NG_VALUE_ACCESSOR_20_6 = [this._DefaultValueAccessor_20_3.context];
    this._NgModel_20_7 = new import17.Wrapper_NgModel(this._ControlContainer_9_4,this._NG_VALIDATORS_20_5,(null as any),this._NG_VALUE_ACCESSOR_20_6);
    this._NgControl_20_8 = this._NgModel_20_7.context;
    this._NgControlStatus_20_9 = new import14.Wrapper_NgControlStatus(this._NgControl_20_8);
    this._text_21 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._text_22 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._text_23 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_9,'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'div',new import3.InlineArray2(2,'class','flex-item full-width'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Dynatrace API Token',(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_26,'input',new import3.InlineArray8(8,'name','token','placeholder','IYVTz0nBSkZdsQOhS7W3P','required','','type','text'),(null as any));
    this._DefaultValueAccessor_31_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_31));
    this._RequiredValidator_31_4 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_31_5 = [this._RequiredValidator_31_4.context];
    this._NG_VALUE_ACCESSOR_31_6 = [this._DefaultValueAccessor_31_3.context];
    this._NgModel_31_7 = new import17.Wrapper_NgModel(this._ControlContainer_9_4,this._NG_VALIDATORS_31_5,(null as any),this._NG_VALUE_ACCESSOR_31_6);
    this._NgControl_31_8 = this._NgModel_31_7.context;
    this._NgControlStatus_31_9 = new import14.Wrapper_NgControlStatus(this._NgControl_31_8);
    this._text_32 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._text_33 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_34 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_9,'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'div',new import3.InlineArray2(2,'class','flex-item next'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'\n                    ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_37,'button',new import3.InlineArray4(4,'class','nextBtn','type','submit'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Continue',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._text_42 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._text_43 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_45 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_9));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_20));
    this._NgModel_20_7.subscribe(this,this.eventHandler(this.handleEvent_20),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_31,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_31));
    this._NgModel_31_7.subscribe(this,this.eventHandler(this.handleEvent_31),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import20.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import18.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import20.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import21.DefaultValueAccessor) && (20 === requestNodeIndex))) { return this._DefaultValueAccessor_20_3.context; }
    if (((token === import22.RequiredValidator) && (20 === requestNodeIndex))) { return this._RequiredValidator_20_4.context; }
    if (((token === import23.NG_VALIDATORS) && (20 === requestNodeIndex))) { return this._NG_VALIDATORS_20_5; }
    if (((token === import24.NG_VALUE_ACCESSOR) && (20 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_20_6; }
    if (((token === import25.NgModel) && (20 === requestNodeIndex))) { return this._NgModel_20_7.context; }
    if (((token === import26.NgControl) && (20 === requestNodeIndex))) { return this._NgControl_20_8; }
    if (((token === import27.NgControlStatus) && (20 === requestNodeIndex))) { return this._NgControlStatus_20_9.context; }
    if (((token === import21.DefaultValueAccessor) && (31 === requestNodeIndex))) { return this._DefaultValueAccessor_31_3.context; }
    if (((token === import22.RequiredValidator) && (31 === requestNodeIndex))) { return this._RequiredValidator_31_4.context; }
    if (((token === import23.NG_VALIDATORS) && (31 === requestNodeIndex))) { return this._NG_VALIDATORS_31_5; }
    if (((token === import24.NG_VALUE_ACCESSOR) && (31 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_31_6; }
    if (((token === import25.NgModel) && (31 === requestNodeIndex))) { return this._NgModel_31_7.context; }
    if (((token === import26.NgControl) && (31 === requestNodeIndex))) { return this._NgControl_31_8; }
    if (((token === import27.NgControlStatus) && (31 === requestNodeIndex))) { return this._NgControlStatus_31_9.context; }
    if (((token === import28.NgForm) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NgForm_9_3.context; }
    if (((token === import29.ControlContainer) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._ControlContainer_9_4; }
    if (((token === import27.NgControlStatusGroup) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NgControlStatusGroup_9_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.configService.isWizard;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._NgForm_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    this._NgControlStatusGroup_9_5.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_11_0_0:boolean = !this.context.configService.config['dynatrace'].success;
    this._NgIf_11_6.check_ngIf(currVal_11_0_0,throwOnChange,false);
    this._NgIf_11_6.ngDoCheck(this,this._anchor_11,throwOnChange);
    this._DefaultValueAccessor_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_20_1_0:any = '';
    this._RequiredValidator_20_4.check_required(currVal_20_1_0,throwOnChange,false);
    this._RequiredValidator_20_4.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_20_2_0:any = 'url';
    this._NgModel_20_7.check_name(currVal_20_2_0,throwOnChange,false);
    const currVal_20_2_1:any = this.context.configService.values.dynatrace.url;
    this._NgModel_20_7.check_model(currVal_20_2_1,throwOnChange,false);
    this._NgModel_20_7.ngDoCheck(this,this._el_20,throwOnChange);
    this._NgControlStatus_20_9.ngDoCheck(this,this._el_20,throwOnChange);
    this._DefaultValueAccessor_31_3.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_31_1_0:any = '';
    this._RequiredValidator_31_4.check_required(currVal_31_1_0,throwOnChange,false);
    this._RequiredValidator_31_4.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_31_2_0:any = 'token';
    this._NgModel_31_7.check_name(currVal_31_2_0,throwOnChange,false);
    const currVal_31_2_1:any = this.context.configService.values.dynatrace.token;
    this._NgModel_31_7.check_model(currVal_31_2_1,throwOnChange,false);
    this._NgModel_31_7.ngDoCheck(this,this._el_31,throwOnChange);
    this._NgControlStatus_31_9.ngDoCheck(this,this._el_31,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_11.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_9_5.checkHost(this,this,this._el_9,throwOnChange);
    this._RequiredValidator_20_4.checkHost(this,this,this._el_20,throwOnChange);
    this._NgControlStatus_20_9.checkHost(this,this,this._el_20,throwOnChange);
    this._RequiredValidator_31_4.checkHost(this,this,this._el_31,throwOnChange);
    this._NgControlStatus_31_9.checkHost(this,this,this._el_31,throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_11.destroyNestedViews();
    this._NgModel_20_7.ngOnDestroy();
    this._NgModel_31_7.ngOnDestroy();
    this._NgForm_9_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_ConfigDynatraceComponent1(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 11)) { return new View_ConfigDynatraceComponent2(this.viewUtils,this,11,this._anchor_11,this._vc_11); }
    return (null as any);
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_9_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'submit')) {
      const pd_sub_0:any = ((<any>this.context.doSubmit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_20_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.configService.values.dynatrace.url = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_31(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_31_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.configService.values.dynatrace.token = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ConfigDynatraceComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ConfigDynatraceComponent1,renderType_ConfigDynatraceComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','step'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Step 2 of 4\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ConfigDynatraceComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ConfigDynatraceComponent2,renderType_ConfigDynatraceComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_5 = import30.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'section',new import3.InlineArray2(2,'class','flex-container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','flex-item full-width error'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5:any = import3.inlineInterpolate(1,'\n                    ',this.parentView.context.configService.config['dynatrace'].error,'\n                ');
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}