'use strict';

module.exports = [
  'alexa stop',
  'bye',
  'exit',
  "I don't need any help",
  "I'm finished",
  'leave me alone',
  'never mind',
  "no, that's all",
  'nope, not at the moment',
  'nothing {{DATETIME}}',
  'nothing',
  "nothing, that's it",
  'off',
  'see ya davis',
  'see ya',
  'shut up',
  'talk to you later',
  "thanks that's it",
  'thanks thats all',
  "that's it for {{DATETIME}}",
  'get lost',
  'end',
  'die',
  'go away',
];
